/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2020-02-04 08:03:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Logica.Tipo;
import Logica.Categoria;
import java.util.List;

public final class crear_005fproducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Logica.Categoria");
    _jspx_imports_classes.add("Logica.Tipo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession sesion = request.getSession(true);
    Object u = sesion.getAttribute("nombre_usuario") == null ? null : sesion.getAttribute("nombre_usuario");
    if(u == null){
        response.sendRedirect("index.jsp");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        \n");
      out.write("        <script src=\"bootstrap/js/jquery-3.3.1.slim.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"bootstrap/js/popper.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link href=\"bootstrap/css/bootstrap-grid.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"bootstrap/css/bootstrap-reboot.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"css/estilo-principal.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        \n");
      out.write("        <script src=\"bootstrap/js/bootstrap.bundle.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        \n");
      out.write("        <script src=\"js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"js/jquery.validate.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"js/additional-methods.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"js/producto_crear.js\" type=\"text/javascript\"></script>\n");
      out.write("        \n");
      out.write("        <title>Crear Productoo</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <header style=\"position: fixed;\">\n");
      out.write("            <h1>Sistema Deposito</h1>\n");
      out.write("        </header>\n");
      out.write("        <nav class=\"navbar navbar-dark default-color\" style=\"position: fixed;\">\n");
      out.write("            <div class=\"dropdown\">\n");
      out.write("                <a style=\"color: yellow;\" class=\"navbar-toggler nav-link dropdown-toggle\" id=\"home\" data-toggle=\"dropdown\"><span class=\"navbar-toggler-icon\"></span>Home</a>\n");
      out.write("                <div class=\"dropdown-menu text-center menu\">\n");
      out.write("                    <form action=\"HomeIr\" method=\"POST\"><input type=\"submit\" style=\"color: yellow;\" value=\"Productos\" class=\"dropdown-item\" id=\"home\"/></form>\n");
      out.write("                    <div class=\"dropdown-divider\" style=\"border-color: yellow;border-width: 3px;\"></div>\n");
      out.write("                    <form action=\"CategoriaTipo\" method=\"POST\"><input type=\"submit\" style=\"color: yellow;\" value=\"Categorias y Tipos\" class=\"dropdown-item\" id=\"cat_tipo\"/></form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"dropdown\" style=\" padding-right: 3em;\">\n");
      out.write("                <a style=\"color: yellow;\" href=\"#\" class=\"navbar-toggler nav-link dropdown-toggle\" id=\"cerrar\" data-toggle=\"dropdown\"> Usuario</a>\n");
      out.write("                <div class=\"dropdown-menu text-center menu\">\n");
      out.write("                    <a><img src=\"img/images-removebg-preview.png\" alt=\"\" style=\"width: 80px; height: 80px;\"/></a><br>\n");
      out.write("                    <a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombre_usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                    <div class=\"dropdown-divider\" style=\"border-color: yellow;border-width: 3px;\"></div>\n");
      out.write("                    <a href=\"modificar_usuario.jsp\"  class=\"dropdown-item\" id=\"mod_usuario\" style=\"color: yellow;\">Modificar Usuario</a>\n");
      out.write("                    <div class=\"dropdown-divider\" style=\"border-color: yellow;border-width: 3px;\"></div>\n");
      out.write("                    <a href=\"CerrarSesion\"  class=\"dropdown-item\" id=\"salir\" style=\"color: yellow;\">Salir</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <main>\n");
      out.write("            <div class=\"container\" id=\"productos\">\n");
      out.write("                <div class=\"row\" style=\"justify-content: center; margin-top: 200px;\">\n");
      out.write("                    <h2 class=\"text-center\">PRODUCTOS</h2>\n");
      out.write("                </div>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <div class=\"row\" style=\"justify-content: center;\">\n");
      out.write("                    <div class=\"container col-md-9\" id=\"datos\" style=\"color: green;\">\n");
      out.write("                        <form name=\"frm_crear_producto\" id=\"frm_crear_producto\" action=\"guardar_producto\" method=\"POST\">\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <h3><strong>CREAR PRODUCTO</strong></h3>\n");
      out.write("                                <br>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <label>Nombre:</label>\n");
      out.write("                                    <input class=\"form-control\" type=\"text\" name=\"nombre\" id=\"nombre_producto\" placeholder=\"nombre del producto\" maxlength=\"25\" required style=\"border-width: 2px; border-style: solid; border-color: green;\"/>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <label>Categoria:</label>\n");
      out.write("                                    <select class=\"form-control\" name=\"categoria\" id=\"select_categoria\" style=\"border-width: 2px; border-style: solid; border-color: green;\">\n");
      out.write("                                        <option value=\"0\">Seleccione una Catgoria</option>\n");
      out.write("                                        ");

                                            List<Categoria> misCategorias = (List<Categoria>) session.getAttribute("categorias");
                                            for(Categoria unaCategoria : misCategorias){
                                                out.println("<option value=\""+ unaCategoria.getCodigo() +"\">"+ unaCategoria.getNombre() +"</option>");
                                            }
                                        
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <label>Tipo:</label>\n");
      out.write("                                    <select class=\"form-control\" name=\"tipo\" id=\"select_tipo\" style=\"border-width: 2px; border-style: solid; border-color: green;\">\n");
      out.write("                                        <option value=\"0\">Seleccione un Tipo</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <label>Precio Costo:</label>\n");
      out.write("                                    <input class=\"form-control\" type=\"number\" name=\"precio_costo\" id=\"precio_costo\" placeholder=\"00.00\" maxlength=\"10\" min=\"0\" max=\"9999999\" step=\".01\" required style=\"border-width: 2px; border-style: solid; border-color: green;\"/>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <label>Precio Venta:</label>\n");
      out.write("                                    <input class=\"form-control\" type=\"number\" name=\"precio_venta\" id=\"precio_venta\" placeholder=\"00.00\" maxlength=\"10\" min=\"0\" max=\"9999999\" step=\".01\" required style=\"border-width: 2px; border-style: solid; border-color: green;\"/>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-2\">\n");
      out.write("                                    <label>Stock:</label>\n");
      out.write("                                    <input class=\"form-control\" type=\"number\" name=\"stock\" id=\"stock\" placeholder=\"00\" maxlength=\"6\" min=\"0\" max=\"999999\" step=\"1\" required style=\"border-width: 2px; border-style: solid; border-color: green;\"/>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-2\">\n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <br>\n");
      out.write("                                    <input class=\"btn btn-danger btn-block\" type=\"submit\" name=\"accion\" value=\"Guardar Producto\" title=\"Guardar el nuevo Producto\"/>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group col-md-4\">\n");
      out.write("                                    <br>\n");
      out.write("                                    <input class=\"btn btn-danger btn-block\" type=\"button\" name=\"cancelar\" value=\"Cancelar\" onclick=\"window.location.href='home.jsp';\" title=\"Volver a Home\"/>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </main>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
